### Spark notebook ###

This notebook will only work in a Jupyter notebook or Jupyter lab session running on the cluster master node in the cloud.

Follow the instructions on the computing resources page to start a cluster and open this notebook.

**Steps**

1. Connect to the Windows server using Windows App.
2. Connect to Kubernetes.
3. Start Jupyter and open this notebook from Jupyter in order to connect to Spark.

In [1]:
# Run this cell to import pyspark and to define start_spark() and stop_spark()

import findspark

findspark.init()

import getpass
import pandas
import pyspark
import random
import re

from IPython.display import display, HTML
from pyspark import SparkContext
from pyspark.sql import SparkSession


# Constants used to interact with Azure Blob Storage using the hdfs command or Spark

global username

username = re.sub('@.*', '', getpass.getuser())

global azure_account_name
global azure_data_container_name
global azure_user_container_name
global azure_user_token

azure_account_name = "madsstorage002"
azure_data_container_name = "campus-data"
azure_user_container_name = "campus-user"
azure_user_token = r"sp=racwdl&st=2024-09-19T08:03:31Z&se=2025-09-19T16:03:31Z&spr=https&sv=2022-11-02&sr=c&sig=kMP%2BsBsRzdVVR8rrg%2BNbDhkRBNs6Q98kYY695XMRFDU%3D"


# Functions used below

def dict_to_html(d):
    """Convert a Python dictionary into a two column table for display.
    """

    html = []

    html.append(f'<table width="100%" style="width:100%; font-family: monospace;">')
    for k, v in d.items():
        html.append(f'<tr><td style="text-align:left;">{k}</td><td>{v}</td></tr>')
    html.append(f'</table>')

    return ''.join(html)


def show_as_html(df, n=20):
    """Leverage existing pandas jupyter integration to show a spark dataframe as html.
    
    Args:
        n (int): number of rows to show (default: 20)
    """

    display(df.limit(n).toPandas())

    
def display_spark():
    """Display the status of the active Spark session if one is currently running.
    """
    
    if 'spark' in globals() and 'sc' in globals():

        name = sc.getConf().get("spark.app.name")

        html = [
            f'<p><b>Spark</b></p>',
            f'<p>The spark session is <b><span style="color:green">active</span></b>, look for <code>{name}</code> under the running applications section in the Spark UI.</p>',
            f'<ul>',
            f'<li><a href="http://localhost:{sc.uiWebUrl.split(":")[-1]}" target="_blank">Spark Application UI</a></li>',
            f'</ul>',
            f'<p><b>Config</b></p>',
            dict_to_html(dict(sc.getConf().getAll())),
            f'<p><b>Notes</b></p>',
            f'<ul>',
            f'<li>The spark session <code>spark</code> and spark context <code>sc</code> global variables have been defined by <code>start_spark()</code>.</li>',
            f'<li>Please run <code>stop_spark()</code> before closing the notebook or restarting the kernel or kill <code>{name}</code> by hand using the link in the Spark UI.</li>',
            f'</ul>',
        ]
        display(HTML(''.join(html)))
        
    else:
        
        html = [
            f'<p><b>Spark</b></p>',
            f'<p>The spark session is <b><span style="color:red">stopped</span></b>, confirm that <code>{username} (notebook)</code> is under the completed applications section in the Spark UI.</p>',
            f'<ul>',
            f'<li><a href="http://mathmadslinux2p.canterbury.ac.nz:8080/" target="_blank">Spark UI</a></li>',
            f'</ul>',
        ]
        display(HTML(''.join(html)))


# Functions to start and stop spark

def start_spark(executor_instances=2, executor_cores=1, worker_memory=1, master_memory=1):
    """Start a new Spark session and define globals for SparkSession (spark) and SparkContext (sc).
    
    Args:
        executor_instances (int): number of executors (default: 2)
        executor_cores (int): number of cores per executor (default: 1)
        worker_memory (float): worker memory (default: 1)
        master_memory (float): master memory (default: 1)
    """

    global spark
    global sc

    cores = executor_instances * executor_cores
    partitions = cores * 4
    port = 4000 + random.randint(1, 999)

    spark = (
        SparkSession.builder
        .config("spark.driver.extraJavaOptions", f"-Dderby.system.home=/tmp/{username}/spark/")
        .config("spark.dynamicAllocation.enabled", "false")
        .config("spark.executor.instances", str(executor_instances))
        .config("spark.executor.cores", str(executor_cores))
        .config("spark.cores.max", str(cores))
        .config("spark.driver.memory", f'{master_memory}g')
        .config("spark.executor.memory", f'{worker_memory}g')
        .config("spark.driver.maxResultSize", "0")
        .config("spark.sql.shuffle.partitions", str(partitions))
        .config("spark.kubernetes.container.image", "madsregistry001.azurecr.io/hadoop-spark:v3.3.5-openjdk-8")
        .config("spark.kubernetes.container.image.pullPolicy", "IfNotPresent")
        .config("spark.kubernetes.memoryOverheadFactor", "0.3")
        .config("spark.memory.fraction", "0.1")
        .config(f"fs.azure.sas.{azure_user_container_name}.{azure_account_name}.blob.core.windows.net",  azure_user_token)
        .config("spark.app.name", f"{username} (notebook)")
        .getOrCreate()
    )
    sc = SparkContext.getOrCreate()
    
    display_spark()

    
def stop_spark():
    """Stop the active Spark session and delete globals for SparkSession (spark) and SparkContext (sc).
    """

    global spark
    global sc

    if 'spark' in globals() and 'sc' in globals():

        spark.stop()

        del spark
        del sc

    display_spark()


# Make css changes to improve spark output readability

html = [
    '<style>',
    'pre { white-space: pre !important; }',
    'table.dataframe td { white-space: nowrap !important; }',
    'table.dataframe thead th:first-child, table.dataframe tbody th { display: none; }',
    '</style>',
]
display(HTML(''.join(html)))

### Assignment 1 ###

The code below demonstrates how to explore and load the data provided for the assignment from Azure Blob Storage and how to save any outputs that you generate to a separate user container.

**Key points**

- The data provided for the assignment is stored in Azure Blob Storage and outputs that you generate will be stored in Azure Blob Storage as well. Hadoop and Spark can both interact with Azure Blob Storage similar to how they interact with HDFS, but where the replication and distribution is handled by Azure instead. This makes it possible to read or write data in Azure over HTTPS where the path is prefixed by `wasbs://`.
- There are two containers, one for the data which is read only and one for any outputs that you generate,
  - `wasbs://campus-data@madsstorage002.blob.core.windows.net/`
  - `wasbs://campus-user@madsstorage002.blob.core.windows.net/`
- You can use variable interpolation to insert your global username variable into paths automatically.
  - This works for bash commands as well.

In [2]:
# Run this cell to start a spark session in this notebook

start_spark(executor_instances=4, executor_cores=2, worker_memory=4, master_memory=4)

Warning: Ignoring non-Spark config property: fs.azure.sas.campus-user.madsstorage002.blob.core.windows.net
Warning: Ignoring non-Spark config property: SPARK_DRIVER_BIND_ADDRESS
25/04/09 11:10:03 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).

In [3]:
# Write your imports here or insert cells below

from pyspark.sql import functions as F
from pyspark.sql.types import *

### Analysis Q1
#### (a) How many stations are there in total? How many stations were active so far in 2025?

In [4]:
# Define an output path

enriched_stations_relative_path = f'{username}/stations_df'
enriched_stations_path = f'wasbs://{azure_user_container_name}@{azure_account_name}.blob.core.windows.net/{enriched_stations_relative_path}'

print(enriched_stations_path)

wasbs://campus-user@madsstorage002.blob.core.windows.net/yya142/stations_df

In [5]:
# Define the enriched stations schema 
schema = StructType([
    StructField("ID",             StringType() , False),
    StructField("STATE",          StringType() , True),
    StructField("COUNTRY CODE",   StringType() , True),
    StructField("LATITUDE",       FloatType()  , True),
    StructField("LONGITUDE",      FloatType() , True),
    StructField("ELEVATION",      FloatType() , True),
    StructField("NAME",           StringType() , True),
    StructField("GSN FLAG",       StringType() , True),
    StructField("HCN/CRN FLAG",   StringType() , True),
    StructField("WMO ID",         StringType()  , True),
    StructField("COUNTRY NAME",   StringType() , True),
    StructField("STATE NAME",     StringType() , True),
    StructField("ACTIVE FIRSTYEAR",   IntegerType() , True),
    StructField("ACTIVE LASTYEAR",    IntegerType() , True),
    StructField("DISTINCT ELEMENT",   StringType(), True),
    StructField("DISTINCT ELEMENT COUNT",    IntegerType() , True),
    StructField("CORE ELEMENT COUNT",        IntegerType() , True),
    StructField("OTHER ELEMENT COUNT",       IntegerType() , True),
])

In [6]:
# Load stations_df file into Spark from Azure Blob Storage using spark.read.csv

stations_df = spark.read.csv(enriched_stations_path, schema=schema)

In [7]:
# correct the data type for the array column "DISTINCT ELEMENT"

stations_df = (
    stations_df.withColumn(
        'DISTINCT ELEMENT', F.split(F.regexp_replace(F.col("DISTINCT ELEMENT"), r"(^\[)|(\]$)|(')", ""), ", ")
    )
)

stations_df.printSchema()
show_as_html(stations_df)

root
 |-- ID: string (nullable = true)
 |-- STATE: string (nullable = true)
 |-- COUNTRY CODE: string (nullable = true)
 |-- LATITUDE: float (nullable = true)
 |-- LONGITUDE: float (nullable = true)
 |-- ELEVATION: float (nullable = true)
 |-- NAME: string (nullable = true)
 |-- GSN FLAG: string (nullable = true)
 |-- HCN/CRN FLAG: string (nullable = true)
 |-- WMO ID: string (nullable = true)
 |-- COUNTRY NAME: string (nullable = true)
 |-- STATE NAME: string (nullable = true)
 |-- ACTIVE FIRSTYEAR: integer (nullable = true)
 |-- ACTIVE LASTYEAR: integer (nullable = true)
 |-- DISTINCT ELEMENT: array (nullable = true)
 |    |-- element: string (containsNull = false)
 |-- DISTINCT ELEMENT COUNT: integer (nullable = true)
 |-- CORE ELEMENT COUNT: integer (nullable = true)
 |-- OTHER ELEMENT COUNT: integer (nullable = true)

25/04/09 11:11:02 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
25/04/09 11:11:17 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
25/04/09 11:11:32 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
25/04/09 11:11:47 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
25/04/09 11:12:02 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources

,ID,STATE,COUNTRY CODE,LATITUDE,LONGITUDE,ELEVATION,NAME,GSN FLAG,HCN/CRN FLAG,WMO ID,COUNTRY NAME,STATE NAME,ACTIVE FIRSTYEAR,ACTIVE LASTYEAR,DISTINCT ELEMENT,DISTINCT ELEMENT COUNT,CORE ELEMENT COUNT,OTHER ELEMENT COUNT
0,AE000041196,None,AE,25.333000,55.516998,34.000000,SHARJAH INTER. AIRP,GSN,None,41196,United Arab Emirates,None,1944,2025,"[PRCP, TAVG, TMAX, TMIN]",4,3,1
1,AEM00041217,None,AE,24.433001,54.651001,26.799999,ABU DHABI INTL,None,None,41217,United Arab Emirates,None,1983,2025,"[PRCP, TAVG, TMAX, TMIN]",4,3,1
2,AEM00041218,None,AE,24.261999,55.609001,264.899994,AL AIN INTL,None,None,41218,United Arab Emirates,None,1994,2025,"[PRCP, TAVG, TMAX, TMIN]",4,3,1
3,AF000040930,None,AF,35.317001,69.016998,3366.000000,NORTH-SALANG,GSN,None,40930,Afghanistan,None,1973,1992,"[PRCP, SNWD, TAVG, TMAX, TMIN]",5,4,1
4,AFM00040990,None,AF,31.500000,65.849998,1010.000000,KANDAHAR AIRPORT,None,None,40990,Afghanistan,None,1973,2020,"[PRCP, SNWD, TAVG, TMAX, TMIN]",5,4,1
5,AG000060680,None,AG,22.799999,5.433100,1362.000000,TAMANRASSET,GSN,None,60680,Algeria,None,1940,2004,"[PRCP, TAVG, TMAX, TMIN]",4,3,1
6,AGE00147704,None,AG,36.970001,7.790000,161.000000,ANNABA-CAP DE GARDE,None,None,None,Algeria,None,1909,1937,"[PRCP, TMAX, TMIN]",3,3,0
7,AGE00147708,None,AG,36.720001,4.050000,222.000000,TIZI OUZOU,None,None,60395,Algeria,None,1879,2025,"[PRCP, SNWD, TAVG, TMAX, TMIN]",5,4,1
8,AGE00147710,None,AG,36.750000,5.100000,9.000000,BEJAIA-BOUGIE (PORT),None,None,60401,Algeria,None,1909,2009,"[PRCP, TAVG, TMAX, TMIN]",4,3,1
9,AGE00147712,None,AG,36.169998,1.340000,112.000000,ORLEANSVILLE (CHLEF),None,None,None,Algeria,None,1879,1938,"[PRCP, TMAX, TMIN]",3,3,0
10,AGE00147713,None,AG,36.180000,5.400000,1081.000000,SETIF,None,None,None,Algeria,None,1878,1938,"[PRCP, TMAX, TMIN]",3,3,0
11,AGE00147714,None,AG,35.770000,0.800000,78.000000,ORAN-CAP FALCON,None,None,None,Algeria,None,1896,1938,"[PRCP, TMAX, TMIN]",3,3,0
12,AGE00147715,None,AG,35.419998,8.119700,863.000000,TEBESSA,None,None,None,Algeria,None,1879,1938,"[PRCP, TMAX, TMIN]",3,3,0
13,AGE00147717,None,AG,35.200001,0.630000,476.000000,SIDI-BEL-ABBES,None,None,None,Algeria,None,1880,1938,"[PRCP, TMAX, TMIN]",3,3,0
14,AGE00147718,None,AG,34.849998,5.720000,125.000000,BISKRA,None,None,60525,Algeria,None,1880,2025,"[PRCP, TAVG, TMAX, TMIN]",4,3,1
15,AGE00147719,None,AG,33.799702,2.890000,767.000000,LAGHOUAT,None,None,60545,Algeria,None,1888,2025,"[PRCP, TAVG, TMAX, TMIN]",4,3,1
16,AGE00147794,None,AG,36.779999,5.100000,225.000000,BEJAIA-CAP CARBON,None,None,None,Algeria,None,1926,1938,"[TMAX, TMIN]",2,2,0
17,AGM00060360,None,AG,36.821999,7.809000,4.900000,ANNABA,None,None,60360,Algeria,None,1945,2025,"[PRCP, TAVG, TMAX, TMIN]",4,3,1
18,AGM00060367,None,AG,36.900002,8.450000,13.000000,EL-KALA,None,None,60367,Algeria,None,1984,2014,"[PRCP, TAVG, TMAX, TMIN]",4,3,1
19,AGM00060402,None,AG,36.712002,5.070000,6.100000,SOUMMAM,None,None,60402,Algeria,None,1973,2025,"[PRCP, SNWD, TAVG, TMAX, TMIN]",5,4,1

In [8]:
# Count total stations

stations_total = stations_df.select("ID").distinct().count()

print(f"There are {stations_total} stations in total.")

[Stage 1:=======================================>                   (4 + 2) / 6]

There are 129657 stations in total.

In [9]:
# Filter the active stations so far in 2025

active_stations_to_2025 =  stations_df.where(F.col("ACTIVE LASTYEAR") == "2025").count()

print(f"There are {active_stations_to_2025} stations are active so far in 2025.")

There are 30735 stations are active so far in 2025.

#### Count how many stations are in each of the GCOS Surface Network (GSN), the US Historical Climatology Network (HCN), and the US Climate Reference Network (CRN)

In [10]:
# Count stations in GSN

gsn_stations = stations_df.where(F.col("GSN FLAG") == "GSN").count()
print(f"There are {gsn_stations} stations in the GCOS Surface Network (GSN).")

# Count stations in HCN

hcn_stations = stations_df.where(F.col("HCN/CRN FLAG") == "HCN").count()
print(f"There are {hcn_stations} stations in the US Historical Climatology Network (HCN).")

# Count stations in CRN

crn_stations = stations_df.where(F.col("HCN/CRN FLAG") == "CRN").count()
print(f"There are {crn_stations} stations in the US Climate Reference Network (CRN).")

There are 991 stations in the GCOS Surface Network (GSN).
There are 1218 stations in the US Historical Climatology Network (HCN).
There are 234 stations in the US Climate Reference Network (CRN).

#### Count stations that are in more than one of these networks

In [11]:
# Filter stations in both GSN and HCN/CRN are not empty

stations_multiple = stations_df.where(
    (F.col("GSN FLAG") != "") & 
    (F.col("HCN/CRN FLAG") != "")
).count()

print(f"There are {stations_multiple} stations that are in more than one of these networks.")

There are 15 stations that are in more than one of these networks.

#### (b) How many stations are there in the Southern Hemisphere?

In [12]:
# Convert latitude from string to double type

stations_df = stations_df.withColumn("LATITUDE", F.col("LATITUDE").cast(DoubleType()))

# Count stations in the Southen Hemisphere 

stations_df.where(F.col('LATITUDE') < 0).count()

25357

In [13]:
# Count the stations in the territories of the United States around the world, excluding the United States itself

stations_df.where(
    (F.col('COUNTRY NAME').contains('United States'))
    & (F.col('COUNTRY NAME') != 'United States')
).count()

414

#### (c) Count the total number of stations in each country, and join these counts onto countries

In [14]:
# load the countries metadata into spark

countries_relative_path = f'ghcnd/ghcnd-countries.txt'
countries_path = f'wasbs://{azure_data_container_name}@{azure_account_name}.blob.core.windows.net/{countries_relative_path}'

countries = spark.read.text(countries_path)

countries = countries.select(
    F.substring(countries['value'], 1, 2).alias('CODE'),
    F.substring(countries['value'], 4, 61).alias('NAME')
)
show_as_html(countries)

   CODE                             NAME
0    AC             Antigua and Barbuda
1    AE            United Arab Emirates
2    AF                      Afghanistan
3    AG                         Algeria
4    AJ                      Azerbaijan
5    AL                          Albania
6    AM                         Armenia
7    AO                          Angola
8    AQ  American Samoa [United States]
9    AR                       Argentina
10   AS                       Australia
11   AU                         Austria
12   AY                      Antarctica
13   BA                         Bahrain
14   BB                        Barbados
15   BC                        Botswana
16   BD        Bermuda [United Kingdom]
17   BE                         Belgium
18   BF                    Bahamas, The
19   BG                       Bangladesh

In [15]:
# Group by country code and count

total_country_station = (stations_df
                         .select(F.col("COUNTRY CODE"))
                         .groupBy("COUNTRY CODE")
                         .agg(F.count(F.col("COUNTRY CODE")).alias("STATION COUNT"))
)

# Join to countries
enriched_countries = (countries
                         .join(total_country_station.withColumnRenamed("COUNTRY CODE", "CODE"),
                        on="CODE",
                        how="left")
)
show_as_html(enriched_countries)

   CODE                             NAME  STATION COUNT
0    AC             Antigua and Barbuda               2
1    AE            United Arab Emirates               4
2    AF                      Afghanistan              4
3    AG                         Algeria              87
4    AJ                      Azerbaijan              66
5    AL                          Albania              3
6    AM                         Armenia              53
7    AO                          Angola               6
8    AQ  American Samoa [United States]              21
9    AR                       Argentina             101
10   AS                       Australia           17088
11   AU                         Austria              13
12   AY                      Antarctica             102
13   BA                         Bahrain               1
14   BB                        Barbados               1
15   BC                        Botswana              21
16   BD        Bermuda [United Kingdom]               2
17   BE                         Belgium               1
18   BF                    Bahamas, The              72
19   BG                       Bangladesh             10

In [16]:
# Define an output path as an exmaple

output_relative_path = f'{username}/enriched_countries'
output_path = f'wasbs://{azure_user_container_name}@{azure_account_name}.blob.core.windows.net/{output_relative_path}'

# Save table in output directory

enriched_countries.write.mode("overwrite").csv(output_path)

25/04/09 11:12:56 WARN AzureFileSystemThreadPoolExecutor: Disabling threads for Delete operation as thread count 0 is <= 1
25/04/09 11:12:57 WARN AzureFileSystemThreadPoolExecutor: Disabling threads for Delete operation as thread count 0 is <= 1

In [17]:
# load the states metadata into spark

states_relative_path = f'ghcnd/ghcnd-states.txt'
states_path = f'wasbs://{azure_data_container_name}@{azure_account_name}.blob.core.windows.net/{states_relative_path}'

states = spark.read.text(states_path)

states = states.select(
    F.substring(states['value'], 1, 2).alias('CODE'),
    F.substring(states['value'], 4, 47).alias('NAME')
)

In [18]:
# Group by state and count stations

total_state_station = (stations_df.where(F.col("STATE").isNotNull())
                         .select(F.col("STATE"))
                         .groupBy("STATE")
                         .agg(F.count(F.col("STATE")).alias("STATION COUNT"))
)

# Join to states
enriched_states = (states
                         .join(total_state_station.withColumnRenamed("STATE", "CODE"),
                        on="CODE",
                        how="left")
)
show_as_html(enriched_states)

   CODE                                             NAME  STATION COUNT
0    AB                                          ALBERTA           1455
1    AK                                           ALASKA           1049
2    AL  ALABAMA                                                   1151
3    AR                                         ARKANSAS            961
4    AS                                   AMERICAN SAMOA             21
5    AZ                                          ARIZONA           1692
6    BC                                 BRITISH COLUMBIA           1720
7    CA                                       CALIFORNIA           3166
8    CO                                         COLORADO           4784
9    CT                                      CONNECTICUT            434
10   DC                             DISTRICT OF COLUMBIA             18
11   DE                                         DELAWARE            148
12   FL                                          FLORIDA           2244
13   FM                                       MICRONESIA             38
14   GA                                          GEORGIA           1407
15   GU                                             GUAM             34
16   HI                                           HAWAII            802
17   IA                                             IOWA           1106
18   ID                                            IDAHO            846
19   IL                                         ILLINOIS           2234

In [19]:
# Define an output path 

output_relative_path = f'{username}/enriched_states'
output_path = f'wasbs://{azure_user_container_name}@{azure_account_name}.blob.core.windows.net/{output_relative_path}'

# Save table in output directory

enriched_states.write.mode("overwrite").csv(output_path)

25/04/09 11:13:18 WARN AzureFileSystemThreadPoolExecutor: Disabling threads for Delete operation as thread count 0 is <= 1
25/04/09 11:13:19 WARN AzureFileSystemThreadPoolExecutor: Disabling threads for Delete operation as thread count 0 is <= 1

### Analysisi Q2
#### (a) Write a Spark function that computes the geographical distance between two stations using their latitude and longitude as arguments.

In [20]:
# import math functions
from math import radians, cos, sin, asin, sqrt

# define stations geographical distance calculation function

def geographical_distance(lon1, lat1, lon2, lat2):
    """
    Calculate the great circle distance in kilometers between two points 
    on the earth (specified in decimal degrees)
    """
    # convert decimal degrees to radians 
    lon1, lat1, lon2, lat2 = map(radians, [lon1, lat1, lon2, lat2])

    # haversine formula 
    dlon = lon2 - lon1 
    dlat = lat2 - lat1 
    a = sin(dlat/2)**2 + cos(lat1) * cos(lat2) * sin(dlon/2)**2
    c = 2 * asin(sqrt(a)) 
    r = 6371 # Radius of earth in kilometers. Use 3956 for miles. Determines return value units.
    return c * r
    
# Convert the function into a UDF

geographical_distance_udf = F.udf(geographical_distance, FloatType())

In [21]:
# define a small subset of stations limit 100

sub_stations = (stations_df
                .select(
                    F.col("ID"),
                    F.col("NAME"),
                    F.col("LATITUDE"),
                    F.col("LONGITUDE")
                ).limit(100)
    
)

# convert data type for LATITUDE and LONGITUDE to hold a certain level precision
sub_stations = (
    sub_stations.withColumn(
        "LATITUDE", F.col("LATITUDE").cast(DoubleType())
    ).withColumn(
        "LONGITUDE", F.col("LONGITUDE").cast(DoubleType())
    )
)

In [22]:
# Cross join stations subset and remove duplicates

cross_joined_df = (
    sub_stations.withColumnsRenamed(
        {column: column + '_1' 
         for column in sub_stations.columns
        }
    )
    .crossJoin(
        sub_stations.withColumnsRenamed(
        {column: column + '_2' 
         for column in sub_stations.columns
        }
        )
    )
    .withColumn(
        'filter', F.array_sort(F.array(F.col('ID_1'), F.col('ID_2')))
    )
    .dropDuplicates(['filter'])
    .drop('filter')
    .where(F.col('ID_1') != F.col('ID_2'))
)

In [23]:
# Calculate geographical distance between stations

geo_distance_df = (
    cross_joined_df.withColumn(
        'DISTANCE', geographical_distance_udf(
            F.col('LONGITUDE_1'), 
            F.col('LATITUDE_1'), 
            F.col('LONGITUDE_2'), 
            F.col('LATITUDE_2')
        )
    )
)

show_as_html(geo_distance_df)

,ID_1,NAME_1,LATITUDE_1,LONGITUDE_1,ID_2,NAME_2,LATITUDE_2,LONGITUDE_2,DISTANCE
0,ACW00011604,ST JOHNS COOLIDGE FLD,17.116699,-61.783298,ACW00011647,ST JOHNS,17.133301,-61.783298,1.846009
1,ACW00011604,ST JOHNS COOLIDGE FLD,17.116699,-61.783298,AEM00041194,DUBAI INTL,25.254999,55.363998,11741.516602
2,ACW00011604,ST JOHNS COOLIDGE FLD,17.116699,-61.783298,AFM00040938,HERAT,34.209999,62.228001,11793.141602
3,ACW00011604,ST JOHNS COOLIDGE FLD,17.116699,-61.783298,AFM00040948,KABUL INTL,34.566002,69.211998,12280.772461
4,ACW00011604,ST JOHNS COOLIDGE FLD,17.116699,-61.783298,AG000060390,ALGER-DAR EL BEIDA,36.716702,3.250000,6676.668457
5,ACW00011604,ST JOHNS COOLIDGE FLD,17.116699,-61.783298,AG000060590,EL-GOLEA,30.566700,2.866700,6657.008301
6,ACW00011604,ST JOHNS COOLIDGE FLD,17.116699,-61.783298,AG000060611,IN-AMENAS,28.049999,9.633100,7335.649414
7,ACW00011604,ST JOHNS COOLIDGE FLD,17.116699,-61.783298,AGE00135039,ORAN-HOPITAL MILITAIRE,35.729698,0.650000,6441.874512
8,ACW00011604,ST JOHNS COOLIDGE FLD,17.116699,-61.783298,AGE00147705,ALGIERS-VILLE/UNIVERSITE,36.779999,3.070000,6660.683105
9,ACW00011604,ST JOHNS COOLIDGE FLD,17.116699,-61.783298,AGE00147706,ALGIERS-BOUZAREAH,36.799999,3.030000,6657.141113
10,ACW00011604,ST JOHNS COOLIDGE FLD,17.116699,-61.783298,AGE00147707,ALGIERS-CAP CAXINE,36.799999,3.040000,6658.031250
11,ACW00011604,ST JOHNS COOLIDGE FLD,17.116699,-61.783298,AGE00147709,FORT NATIONAL,36.630001,4.200000,6761.386719
12,ACW00011604,ST JOHNS COOLIDGE FLD,17.116699,-61.783298,AGE00147711,CONSTANTINE,36.369701,6.620000,6978.187500
13,ACW00011604,ST JOHNS COOLIDGE FLD,17.116699,-61.783298,AGE00147716,NEMOURS (GHAZAOUET),35.099998,-1.850000,6213.181641
14,ACW00011604,ST JOHNS COOLIDGE FLD,17.116699,-61.783298,AGE00147720,GERYVILLE (EL-BAYADH),33.680000,1.000000,6471.609863
15,ACW00011604,ST JOHNS COOLIDGE FLD,17.116699,-61.783298,AGE00147780,SKIKDA-CAP BOUGAROUNI,37.080002,6.470000,6962.614258
16,ACW00011604,ST JOHNS COOLIDGE FLD,17.116699,-61.783298,AGM00060351,JIJEL,36.794998,5.874000,6910.360840
17,ACW00011604,ST JOHNS COOLIDGE FLD,17.116699,-61.783298,AGM00060353,JIJEL-PORT,36.817001,5.883000,6911.112305
18,ACW00011604,ST JOHNS COOLIDGE FLD,17.116699,-61.783298,AGM00060355,SKIKDA,36.932999,6.950000,7005.664551
19,ACW00011604,ST JOHNS COOLIDGE FLD,17.116699,-61.783298,AGM00060369,ALGER-PORT,36.766998,3.100000,6663.342773

#### (b) Applying Distance Function to New Zealand Stations

In [24]:
# define a small subset of stations limit 100

stations_nz = (stations_df
                .select(
                    F.col("ID"),
                    F.col("NAME"),
                    F.col("LATITUDE"),
                    F.col("LONGITUDE"),
                ).where(F.col('COUNTRY CODE') == 'NZ')
    
)

# convert data type for LATITUDE and LONGITUDE to hold a certain level precision
stations_nz = (
    stations_nz.withColumn(
        "LATITUDE", F.col("LATITUDE").cast(DoubleType())
    ).withColumn(
        "LONGITUDE", F.col("LONGITUDE").cast(DoubleType())
    )
)

In [25]:
# Cross join stations subset and remove duplicates

cross_joined_df_nz = (
    stations_nz.withColumnsRenamed(
        {column: column + '_1' 
         for column in sub_stations.columns
        }
    )
    .crossJoin(
        stations_nz.withColumnsRenamed(
        {column: column + '_2' 
         for column in sub_stations.columns
        }
        )
    )
    .withColumn(
        'filter', F.array_sort(F.array(F.col('ID_1'), F.col('ID_2')))
    )
    .dropDuplicates(['filter'])
    .drop('filter')
    .where(F.col('ID_1') != F.col('ID_2'))
)

In [26]:
# Calculate geographical distance between stations

geo_distance_df_nz = (
    cross_joined_df_nz.withColumn(
        'DISTANCE', geographical_distance_udf(
            F.col('LONGITUDE_1'), 
            F.col('LATITUDE_1'), 
            F.col('LONGITUDE_2'), 
            F.col('LATITUDE_2')
        )
    )
).orderBy("DISTANCE", ascending=True)

show_as_html(geo_distance_df_nz)

,ID_1,NAME_1,LATITUDE_1,LONGITUDE_1,ID_2,NAME_2,LATITUDE_2,LONGITUDE_2,DISTANCE
0,NZ000093417,PARAPARAUMU AWS,-40.900002,174.983002,NZM00093439,WELLINGTON AERO AWS,-41.333000,174.800003,50.528851
1,NZM00093678,KAIKOURA,-42.417000,173.699997,NZM00093439,WELLINGTON AERO AWS,-41.333000,174.800003,151.071701
2,NZ000936150,HOKITIKA AERODROME,-42.716999,170.983002,NZM00093781,CHRISTCHURCH INTL,-43.488998,172.531998,152.258041
3,NZM00093678,KAIKOURA,-42.417000,173.699997,NZM00093781,CHRISTCHURCH INTL,-43.488998,172.531998,152.458817
4,NZ000093417,PARAPARAUMU AWS,-40.900002,174.983002,NZM00093678,KAIKOURA,-42.417000,173.699997,199.529678
5,NZ000936150,HOKITIKA AERODROME,-42.716999,170.983002,NZ000937470,TARA HILLS,-44.516998,169.899994,218.309189
6,NZ000093417,PARAPARAUMU AWS,-40.900002,174.983002,NZ000933090,NEW PLYMOUTH AWS,-39.016998,174.182999,220.200211
7,NZ000936150,HOKITIKA AERODROME,-42.716999,170.983002,NZM00093678,KAIKOURA,-42.417000,173.699997,224.980881
8,NZM00093110,AUCKLAND AERO AWS,-37.000000,174.800003,NZ000933090,NEW PLYMOUTH AWS,-39.016998,174.182999,230.700760
9,NZ000937470,TARA HILLS,-44.516998,169.899994,NZM00093781,CHRISTCHURCH INTL,-43.488998,172.531998,239.530396
10,NZ000093844,INVERCARGILL AIRPOR,-46.417000,168.332993,NZ000937470,TARA HILLS,-44.516998,169.899994,244.053162
11,NZM00093110,AUCKLAND AERO AWS,-37.000000,174.800003,NZ000093012,KAITAIA,-35.099998,173.266998,252.239044
12,NZ000933090,NEW PLYMOUTH AWS,-39.016998,174.182999,NZM00093439,WELLINGTON AERO AWS,-41.333000,174.800003,262.806671
13,NZM00093781,CHRISTCHURCH INTL,-43.488998,172.531998,NZM00093439,WELLINGTON AERO AWS,-41.333000,174.800003,303.524353
14,NZ000939450,CAMPBELL ISLAND AWS,-52.549999,169.167007,NZM00093929,ENDERBY ISLAND AWS,-50.483002,166.300003,303.566681
15,NZ000093292,GISBORNE AERODROME,-38.650002,177.983002,NZ000933090,NEW PLYMOUTH AWS,-39.016998,174.182999,331.642334
16,NZM00093110,AUCKLAND AERO AWS,-37.000000,174.800003,NZ000093292,GISBORNE AERODROME,-38.650002,177.983002,334.360809
17,NZ000936150,HOKITIKA AERODROME,-42.716999,170.983002,NZM00093439,WELLINGTON AERO AWS,-41.333000,174.800003,350.796082
18,NZ000093417,PARAPARAUMU AWS,-40.900002,174.983002,NZM00093781,CHRISTCHURCH INTL,-43.488998,172.531998,351.596313
19,NZ000093417,PARAPARAUMU AWS,-40.900002,174.983002,NZ000093292,GISBORNE AERODROME,-38.650002,177.983002,358.180542

### Analysisi Q3
#### (a) Count the number of rows in daily.

In [27]:
# Define the schema for daily

schema_daily = StructType([
    StructField("ID",      StringType() , False),
    StructField("DATE",    StringType() , True),
    StructField("ELEMENT", StringType() , True),
    StructField("VALUE",   FloatType()  , True),
    StructField("MEASUREMENT FLAG",  StringType() , True),
    StructField("QUALITY FLAG",      StringType() , True),
    StructField("SOURCE FLAG",       StringType() , True),
    StructField("OBSERVATION TIME",  StringType() , True),
])

In [28]:
# Define the input path for daily

daily_relative_path = f'ghcnd/daily/*.csv.gz'
daily_path = f'wasbs://{azure_data_container_name}@{azure_account_name}.blob.core.windows.net/{daily_relative_path}'

# Load daily CSV files into Spark dataframe

daily_raw = spark.read.csv(daily_path, schema=schema_daily)

# Correct the data type for the date column

daily = daily_raw.withColumn(
    "DATE", F.to_date("DATE", "yyyyMMdd")
)

# Count the nuber of rows in daily

daily_total_count = daily.count()

print(f'There are {daily_total_count} rows in all daily files.')

[Stage 55:=====================================================>(105 + 1) / 106]

There are 3139143397 rows in all daily files.

#### (b) How many observations are there for each of the five core elements?

In [29]:
# Define the core elements

core_elements = ['TMAX', 'TMIN', 'PRCP', 'SNOW', 'SNWD']

# Filter the observations containing the core elements

daily_core_elements = daily.where(F.col('ELEMENT').isin(core_elements))

# Count the number of observations for each core element

daily_core_elements_count = (
    daily_core_elements.select('ELEMENT')
    .groupBy('ELEMENT')
    .agg(
        F.count(F.col('ELEMENT')).alias('OBSERVATION COUNT')
    )
)

daily_core_elements_count.cache()

show_as_html(daily_core_elements_count)

  ELEMENT  OBSERVATION COUNT
0    SNWD          300711620
1    SNOW          359249644
2    TMIN          458928768
3    PRCP         1079767077
4    TMAX          460114659

#### Which element has the most observations?

In [30]:
# Sort the core element count dataframe descending by counted observation results

daily_core_elements_count_sort = daily_core_elements_count.orderBy('OBSERVATION COUNT', ascending=False)

show_as_html(daily_core_elements_count_sort)

  ELEMENT  OBSERVATION COUNT
0    PRCP         1079767077
1    TMAX          460114659
2    TMIN          458928768
3    SNOW          359249644
4    SNWD          300711620

In [31]:
daily_tmax_only = (
    daily_core_elements.where(
        F.col('ELEMENT').isin(['TMAX', 'TMIN'])
    ).show()
)

+-----------+----------+-------+-----+----------------+------------+-----------+----------------+
|         ID|      DATE|ELEMENT|VALUE|MEASUREMENT FLAG|QUALITY FLAG|SOURCE FLAG|OBSERVATION TIME|
+-----------+----------+-------+-----+----------------+------------+-----------+----------------+
|ASN00038000|2010-01-01|   TMAX|404.0|            NULL|        NULL|          a|            NULL|
|ASN00038000|2010-01-01|   TMIN|250.0|            NULL|        NULL|          a|            NULL|
|ASN00038003|2010-01-01|   TMAX|383.0|            NULL|        NULL|          a|            NULL|
|ASN00038003|2010-01-01|   TMIN|236.0|            NULL|        NULL|          a|            NULL|
|ASN00038024|2010-01-01|   TMAX|351.0|            NULL|        NULL|          a|            NULL|
|ASN00038024|2010-01-01|   TMIN|245.0|            NULL|        NULL|          a|            NULL|
|ASN00038026|2010-01-01|   TMAX|407.0|            NULL|        NULL|          a|            NULL|
|ASN00038026|2010-01-01|   TMIN|285.0|            NULL|        NULL|          a|            NULL|
|ASN00004028|2010-01-01|   TMAX|380.0|            NULL|        NULL|          a|            NULL|
|ASN00004032|2010-01-01|   TMAX|416.0|            NULL|        NULL|          a|            NULL|
|ASN00004032|2010-01-01|   TMIN|247.0|            NULL|        NULL|          a|            NULL|
|ASN00004035|2010-01-01|   TMAX|461.0|            NULL|        NULL|          a|            NULL|
|ASN00004035|2010-01-01|   TMIN|263.0|            NULL|        NULL|          a|            NULL|
|ASN00041175|2010-01-01|   TMAX|242.0|            NULL|        NULL|          a|            NULL|
|ASN00041175|2010-01-01|   TMIN|167.0|            NULL|        NULL|          a|            NULL|
|ASN00043091|2010-01-01|   TMAX|268.0|            NULL|        NULL|          a|            NULL|
|ASN00043091|2010-01-01|   TMIN|213.0|            NULL|        NULL|          a|            NULL|
|ASN00043109|2010-01-01|   TMAX|257.0|            NULL|        NULL|          a|            NULL|
|ASN00043109|2010-01-01|   TMIN|218.0|            NULL|        NULL|          a|            NULL|
|ASN00044010|2010-01-01|   TMAX|267.0|            NULL|        NULL|          a|            NULL|
+-----------+----------+-------+-----+----------------+------------+-----------+----------------+
only showing top 20 rows

#### (c) Determine how many observations of TMAX do not have a corresponding observation of TMIN.

In [32]:
# Count the number of observations on a given day is TMAX with no TMIN

daily_tmax_only = (
    daily_core_elements.where(
        F.col('ELEMENT').isin(['TMAX', 'TMIN'])
    ).groupBy(['ID', 'DATE'])
    .agg(
        F.count(F.col('ID')).alias('OBSERVATION COUNT'), 
        F.first(F.col('ELEMENT')).alias('FIRST ELEMENT')
    ).where(
        (F.col('OBSERVATION COUNT') == 1) 
        & (F.col('FIRST ELEMENT') == 'TMAX')
    )
)

daily_tmax_only_count = daily_tmax_only.count()

print(f'There are {daily_tmax_only_count} observations of TMAX do not have a corresponding observation of TMIN.')

[Stage 68:====================================================>   (30 + 2) / 32]

There are 10660214 observations of TMAX do not have a corresponding observation of TMIN.

In [ ]:
(
    daily_core_elements.where(
        F.col('ELEMENT').isin(['TMAX', 'TMIN'])
    ).groupBy(['ID', 'DATE'])
    .agg(
        F.count(F.col('ID')).alias('OBSERVATION COUNT'), 
        F.first(F.col('ELEMENT')).alias('FIRST ELEMENT')
    ).show()
)

In [ ]:
daily_core_elements.where(
    F.col('ELEMENT').isin(['TMAX', 'TMIN'])
).groupBy(['ID', 'DATE']).agg(
    F.count(F.col('ID')).alias('OBSERVATION COUNT'), 
    F.first(F.col('ELEMENT')).alias('FIRST ELEMENT')
).select('OBSERVATION COUNT').distinct().show()

In [40]:
daily_tmax_only.show()

[Stage 84:>                                                         (0 + 1) / 1]

+-----------+----------+-----------------+-------------+
|         ID|      DATE|OBSERVATION COUNT|FIRST ELEMENT|
+-----------+----------+-----------------+-------------+
|AE000041196|1955-05-08|                1|         TMAX|
|AE000041196|1957-11-12|                1|         TMAX|
|AE000041196|1965-06-07|                1|         TMAX|
|AE000041196|1977-08-29|                1|         TMAX|
|AE000041196|1978-01-16|                1|         TMAX|
|AE000041196|1978-12-08|                1|         TMAX|
|AE000041196|1979-02-13|                1|         TMAX|
|AE000041196|1979-02-24|                1|         TMAX|
|AE000041196|1979-03-30|                1|         TMAX|
|AE000041196|1979-07-19|                1|         TMAX|
|AE000041196|1979-09-21|                1|         TMAX|
|AE000041196|1979-11-24|                1|         TMAX|
|AE000041196|1980-01-08|                1|         TMAX|
|AE000041196|1980-02-05|                1|         TMAX|
|AE000041196|1980-05-20|                1|         TMAX|
|AE000041196|1980-05-24|                1|         TMAX|
|AE000041196|1980-06-09|                1|         TMAX|
|AE000041196|1980-06-22|                1|         TMAX|
|AE000041196|1980-06-23|                1|         TMAX|
|AE000041196|1980-07-24|                1|         TMAX|
+-----------+----------+-----------------+-------------+
only showing top 20 rows

#### How many unique stations contributed to these observations?

In [41]:
# Count how many distinct unique station ID is in the daily_tmax_only dataframe

daily_tmax_only_station_count = daily_tmax_only.select('ID').distinct().count()

print(f'There are {daily_tmax_only_station_count} unique stations contributed to these observations')

[Stage 87:======================================================> (31 + 1) / 32]

There are 28754 unique stations contributed to these observations

### Visualizations Q1
#### (a) Filter daily to obtain all observations of TMIN and TMAX for all stations in New Zealand, and save the result to your output directory.

In [10]:
# Filter for New Zealand stations

nz_tmax_tmin_daily = (
    daily.where(
    (F.col('ELEMENT').isin(['TMAX', 'TMIN']))
    & (F.substring('ID', 1, 2) == 'NZ')
    )
)

show_as_html(nz_tmax_tmin_daily)

,ID,DATE,ELEMENT,VALUE,MEASUREMENT FLAG,QUALITY FLAG,SOURCE FLAG,OBSERVATION TIME
0,NZ000093292,2024-01-01,TMIN,137.0,None,None,S,None
1,NZ000093417,2024-01-01,TMAX,198.0,None,None,S,None
2,NZ000093417,2024-01-01,TMIN,125.0,None,None,S,None
3,NZ000093844,2024-01-01,TMAX,168.0,None,None,S,None
4,NZ000093844,2024-01-01,TMIN,78.0,None,None,S,None
5,NZ000093994,2024-01-01,TMAX,288.0,None,None,S,None
6,NZ000093994,2024-01-01,TMIN,191.0,None,None,S,None
7,NZ000933090,2024-01-01,TMAX,204.0,None,None,S,None
8,NZ000933090,2024-01-01,TMIN,93.0,None,None,S,None
9,NZ000936150,2024-01-01,TMIN,78.0,None,None,S,None
10,NZ000939450,2024-01-01,TMAX,100.0,None,None,S,None
11,NZ000939450,2024-01-01,TMIN,55.0,None,None,S,None
12,NZM00093110,2024-01-01,TMAX,214.0,None,None,S,None
13,NZM00093110,2024-01-01,TMIN,136.0,None,None,S,None
14,NZM00093439,2024-01-01,TMIN,128.0,None,None,S,None
15,NZM00093678,2024-01-01,TMIN,108.0,None,None,S,None
16,NZM00093781,2024-01-01,TMIN,78.0,None,None,S,None
17,NZM00093929,2024-01-01,TMAX,130.0,None,None,S,None
18,NZM00093929,2024-01-01,TMIN,77.0,None,None,S,None
19,NZ000093292,2024-01-02,TMAX,254.0,None,None,S,None

In [11]:
# Save the result to output directory

output_relative_path = f'{username}/nz_tmax_tmin_daily'
output_path = f'wasbs://{azure_user_container_name}@{azure_account_name}.blob.core.windows.net/{output_relative_path}'

nz_tmax_tmin_daily.write.mode("overwrite").csv(output_path)

25/04/07 21:47:58 WARN AzureFileSystemThreadPoolExecutor: Disabling threads for Delete operation as thread count 0 is <= 1

#### How many observations are there, and how many years are covered by the observations?

In [59]:
# Count the number of observations for NZ stations

nz_tmax_tmin_daily_count = nz_tmax_tmin_daily.count()

print(f'There are {nz_tmax_tmin_daily_count} observations of element TMAX and TMIN collected by NZ stations.')

nz_tmax_tmin_daily_count.

[Stage 97:=====================================================>(105 + 1) / 106]

There are 491441 observations are there.

In [15]:
# Count number of distinct years covered by observations in daily

nz_tmax_tmin_daily_year_count = nz_tmax_tmin_daily.select(F.year('DATE')).distinct().count()

print(f'There are {nz_tmax_tmin_daily_year_count} of years covered by the observations.')

[Stage 15:>                                                         (0 + 1) / 1]

There are 1 of years covered by the observations.

#### (b) Plot time series for TMIN and TMAX together for each station in New Zealand using Python, R, or any other programming language or data visualization tool that you know well. Also, plot the average time series for TMIN and TMAX together for the entire country.

In [33]:
# Run this cell before closing the notebook or kill your spark application by hand using the link in the Spark UI

stop_spark()

25/04/09 12:05:43 WARN ExecutorPodsWatchSnapshotSource: Kubernetes client has been closed.